- src/main.py:
    - description: Check file exists
      check: ConfirmFileExists
    - description: Import machine module
      check: MatchFileFragment
      options:
        fragment: from machine import Pin
        count: 1
        exact: false
    - description: Import time module
      check: MatchFileFragment
      options:
        fragment: import time
        count: 1
        exact: false
    - description: Use main function
      check: MatchFileFragment
      options:
        fragment: def main()
        count: 1
        exact: false
    - description: Use main guard
      check: MatchFileFragment
      options:
        fragment: '__main__'
        count: 1
        exact: false
    - description: Create LED list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: led_list
        count: 2
        exact: false
    - description: Create LED names list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: led_names
        count: 2
        exact: false
    - description: Create LED pins list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: led_pins
        count: 2
        exact: false
    - description: Create speed options list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: speed_options
        count: 2
        exact: false
    - description: Create speed names list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: speed_names
        count: 2
        exact: false
    - description: Create pattern names list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: pattern_names
        count: 2
        exact: false
    - description: Create chase speeds list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: chase_speeds
        count: 2
        exact: false
    - description: Create flash durations list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: flash_durations
        count: 2
        exact: false
    - description: Create flash counts list (at least 2 uses)
      check: MatchFileFragment
      options:
        fragment: flash_counts
        count: 2
        exact: false
    - description: Create multiple lists with assignment = [ (check for 9 lists)
      check: MatchFileFragment
      options:
        fragment: ' = ['
        count: 9
        exact: false
    - description: Use list indexing [ (at least 20 times)
      check: MatchFileFragment
      options:
        fragment: '['
        count: 20
        exact: false
    - description: Use range with len for list iteration range(len( (at least 3 times)
      check: MatchFileFragment
      options:
        fragment: range(len(
        count: 3
        exact: false
    - description: Use LED on method .on() (at least 10 times)
      check: MatchFileFragment
      options:
        fragment: .on()
        count: 10
        exact: false
    - description: Use LED off method .off() (at least 10 times)
      check: MatchFileFragment
      options:
        fragment: .off()
        count: 10
        exact: false
    - description: Use sleep calls for timing time.sleep( (at least 15 times)
      check: MatchFileFragment
      options:
        fragment: time.sleep(
        count: 15
        exact: false
    - description: Use print statements for interaction print( (at least 20 times)
      check: MatchFileFragment
      options:
        fragment: print(
        count: 20
        exact: false
    - description: Use input for user interaction input( (at least 3 times)
      check: MatchFileFragment
      options:
        fragment: input(
        count: 3
        exact: false
    - description: Use for loop iteration (at least 6 times)
      check: MatchFileFragment
      options:
        fragment: 'for '
        count: 6
        exact: false
    - description: Use Pin objects for GPIO control Pin( (at least 4 times)
      check: MatchFileFragment
      options:
        fragment: Pin(
        count: 4
        exact: false
    - description: Use list join method .join( (at least 1 time)
      check: MatchFileFragment
      options:
        fragment: .join(
        count: 1
        exact: false
    - description: Complete all TODOs (no TODO comments remaining in main.py)
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: false

- writing/reflection.md:
    - description: Check reflection exists
      check: ConfirmFileExists
    - description: Write sufficient words (at least 250 words)
      check: CountFileWords
      options:
        count: 250
    - description: Use markdown lists using - (at least 8 list items total)
      check: MatchFileFragment
      options:
        fragment: '- '
        count: 10
        exact: false
